[phases.setup]
nixPkgs = ['python313']

[phases.install]
cmds = ['pip install -r requirements.txt']

[start]
cmd = 'python manage.py migrate && gunicorn --bind 0.0.0.0:$PORT app_movil_escolar_api.wsgi:application'
